# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build - wueste

on:
  push:
    # Sequence of patterns matched against refs/tags
    #tags:
    #  - 'dev'
    #  - 'prod'
    branches: [main]

  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Patch Version ${{ env.GITHUB_REF }}
        run: |
          node .github/workflows/patch-package.json.js "origin/head/0.0.0-smoke"
          git diff

      - name: Build JS wueste
        run: |
          npm install
          npm run prettier -- --check
          npm run lint
          npm run build
          npm run test

      - name: Smoke JS wueste
        run: |
          npm run smoke
